### PR TITLE
Added `--quiet`

### PR DESCRIPTION
**Pull request by Billy-Sheppard**
Added abilities to quieten output, and also choose between `stdout` (default) and `stderr` (on a flag).

Also removed use of es!() to make it work, if any of this is unwanted happy to discuss how best to make it work.

### CODE REVIEW

**Comment by andrewbaxter** [comment]
Sorry, conflict after the other mr. This seems fine to me, quiet is probably reasonably necessary.  I'm fine with stderr too, but what's the use case for that?

**Comment by Billy-Sheppard** [comment]
AFAIK the standard use case is to use `println!()` for general information and `eprintln!()` for actual errors. However in my experience being able to use `stdout` or `stderr` is particularly useful when working with CI/CD pipelines. Happy to discuss/look into this further of course.

**Comment by andrewbaxter** [comment]
Ah gotcha.  I think there's a second standard for stdout/stderr which is that because stdout is captured by `|` on the command line, data output (anything that should be consumed) should go to stdout where informational messages, error or otherwise, should go to stderr.

Ex: if you have a command that outputs json, but emits stats like "processed NMiB in Y seconds", the stats should be sent to stderr so the json can be piped to `jq` regardless.

I think that's the convention I'd like to stay with here at least for now, unless it causes something else to blow up.

**Comment by Billy-Sheppard** [comment]
Sounds very reasonable. I've made those changes let me know how it all looks :).

**Comment by andrewbaxter** [comment]
Nice, thanks!

**Comment by andrewbaxter** [comment]
TIL `matches!`, that'll be really helpful...

**Pull request merged**
