### PR TITLE
Only write files on change.

### PR DESCRIPTION
**Pull request by djacu**
When formatting files, genemichaels always writes the formatted file to disk which modifies the file timestamp. This is problematic for tools that detect whether a file has been reformatted or not.

This commit changes the behavior by comparing the source against the formatted output and only writing to disk if they are different.

Fixes https://github.com/andrewbaxter/genemichaels/issues/95

---

I agree that when the request is merged I assign the copyright of the request to the repository owner.

### CODE REVIEW

**Comment by andrewbaxter** [comment]
Oh fantastic! Yeah, we shouldn't have been always writing. Thanks for this!

**Comment by andrewbaxter** [comment]
Ah, that test was something I had for debug dumping output, I should get rid of that.

**Comment by andrewbaxter** [comment]
Released as `0.5.12`.

**Comment by djacu** [comment]
> Ah, that test was something I had for debug dumping output, I should get rid of that.

Do you mean this test that has been failing since 0.5.7?
https://github.com/andrewbaxter/genemichaels/actions/runs/12336988263/job/34430124529

I was going to ask about that since I'd like to add the latest to nixpkgs but stopped at 0.5.7 since the tests after that started failing. See https://github.com/NixOS/nixpkgs/pull/363473

**Comment by andrewbaxter** [comment]
Oh yeah, that one! Sorry, didn't realize it was causing problems externally.  I'll get rid of it now.

**Comment by andrewbaxter** [comment]
Okay as of `0.5.13` that's been removed and the tests are all passing.

**Comment by djacu** [comment]
Not a problem. I thought it was part of a developing test for the new macros crate.

**Pull request merged**
